name: graded_reader
description: "For all those who aspire to read God's word in its original language, this app is designed to take you from simple reading and vocabulary comprehension to praying, conversing, and reading God's word."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.10.0

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/beit_av/
    - assets/fonts/
    - assets/books/

  fonts:
    - family: SBLBibLit
      fonts:
        - asset: assets/fonts/SBL_BLit.ttf

flutter_icons:
  ios: true
  image_path: "assets/images/graded_reader_icon.png"